title: Anonoz Burps
email: hi@anonoz.com
description: >- # this means to ignore newlines until "baseurl:"
  Rails & DevOps fella from KL, Malaysia.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://anonoz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: anonoz
google_analytics: UA-127723772-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
